name: widgets_demonstration
description: A app that demonstrates some flutter default widgets.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts:
  provider: ^4.3.3
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



